# Generated by Django 3.2.4 on 2021-06-25 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0004_emailtemplate'),
        ('tenant', '0003_booking_expired'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('subject', models.CharField(default='', max_length=255)),
                ('sender_email', models.EmailField(max_length=254)),
                ('sender_name', models.CharField(default='', max_length=50)),
                ('recipients', models.JSONField()),
                ('attachments', models.JSONField()),
                ('cc', models.JSONField(default=None, null=True)),
                ('bcc', models.JSONField(default=None, null=True)),
                ('context', models.JSONField()),
                ('template', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shared.emailtemplate')),
            ],
        ),
    ]
