# Generated by Django 3.2.4 on 2021-06-25 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0004_mail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='bcc',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='mail',
            name='cc',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
