# Generated by Django 3.2.4 on 2021-06-25 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0005_auto_20210625_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='attachments',
            field=models.JSONField(blank=True),
        ),
    ]
