# Generated by Django 3.2.4 on 2021-06-29 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0007_auto_20210629_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='attachments',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
