# Generated by Django 3.2.4 on 2021-06-25 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0003_auto_20210625_1403'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('html', models.SmallIntegerField(choices=[(0, 'forgot_password.html'), (1, 'verify_email.html'), (2, 'welcome.html')], default=None, null=True)),
                ('html_body', models.TextField(blank=True, default='')),
                ('template_context', models.JSONField()),
            ],
        ),
    ]
